[tool.poetry]
name = "wavenet_kws"
version = "1.0"
description = ""
authors = ["AndBondStyle <andbondstyle@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
